/*
 * mango/task/MangoTask.h
 *
 * Objective-C class for task and thread management.
 *
 * In real Mach, a task is an address space with port rights and
 * an list of threads.  In Mango's usermode environment, a task
 * maps to a host process (fork/exec).
 */

#ifndef MANGO_TASK_MANGOTASK_H
#define MANGO_TASK_MANGOTASK_H

#include "../mach/mach_types.h"
#include "../mach/mach_port.h"
#include <sys/types.h>
#include <unistd.h>
#include <objc/objc.h>

/* -----------------------------------------------------------------------
 *  Limits
 * ----------------------------------------------------------------------- */

#define TASK_MAX            128
#define TASK_PORT_MAX       64
#define TASK_NAME_MAX       64
#define THREAD_MAX          256

/* -----------------------------------------------------------------------
 *  Thread object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mango_thread {
    mach_thread_t       id;
    pid_t               host_tid;
    BOOL                active;
    BOOL                suspended;
} mango_thread_t;

/* -----------------------------------------------------------------------
 *  Task object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mango_task {
    mach_task_t         id;
    char                name[TASK_NAME_MAX];
    pid_t               host_pid;
    BOOL                in_use;
    BOOL                running;
    BOOL                terminated;

    mach_port_name_t    ports[TASK_PORT_MAX];
    mach_port_t         port_objects[TASK_PORT_MAX];
    int                 port_count;

    mach_port_t         bootstrap_port;

    mango_thread_t     *threads[THREAD_MAX];
    int                 thread_count;

    char                binary_path[512];
    char                userfs_root[512];
} mango_task_t;

/* -----------------------------------------------------------------------
 *  Task table (C globals)
 * ----------------------------------------------------------------------- */

extern mango_task_t  mango_task_table[TASK_MAX];
extern int           mango_task_count;
extern mango_task_t *mango_current_task;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

typedef struct MangoTask {
    struct objc_object *isa;
} MangoTask;

/* Note: Method implementations are auto-generated by objcc preprocessor.
 * The preprocessor outputs function declarations at the start of the .m file.
 */

#endif /* MANGO_TASK_MANGOTASK_H */
