/*
 * mango/task/MangoTask.h
 *
 * Objective-C class for task and thread management.
 *
 * In real Mach, a task is an address space with port rights and
 * an list of threads.  In Mango's usermode environment, a task
 * maps to a host process (fork/exec).
 */

#ifndef MANGO_TASK_MANGOTASK_H
#define MANGO_TASK_MANGOTASK_H

#include "../mach/mach_types.h"
#include "../mach/mach_port.h"
#include <sys/types.h>
#include <unistd.h>

#ifdef __OBJC__
#include <objc/Object.h>
#endif

/* -----------------------------------------------------------------------
 *  Limits
 * ----------------------------------------------------------------------- */

#define TASK_MAX            128
#define TASK_PORT_MAX       64
#define TASK_NAME_MAX       64
#define THREAD_MAX          256

/* -----------------------------------------------------------------------
 *  Thread object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mango_thread {
    mach_thread_t       id;
    pid_t               host_tid;
    BOOL                active;
    BOOL                suspended;
} mango_thread_t;

/* -----------------------------------------------------------------------
 *  Task object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mango_task {
    mach_task_t         id;
    char                name[TASK_NAME_MAX];
    pid_t               host_pid;
    BOOL                in_use;
    BOOL                running;
    BOOL                terminated;

    mach_port_name_t    ports[TASK_PORT_MAX];
    mach_port_t         port_objects[TASK_PORT_MAX];
    int                 port_count;

    mach_port_t         bootstrap_port;

    mango_thread_t     *threads[THREAD_MAX];
    int                 thread_count;

    char                binary_path[512];
    char                userfs_root[512];
} mango_task_t;

/* -----------------------------------------------------------------------
 *  Task table (C globals)
 * ----------------------------------------------------------------------- */

extern mango_task_t  _mango_task_table[TASK_MAX];
extern int           _mango_task_count;
extern mango_task_t *_mango_current_task;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

id   MangoTask_inst_init(MangoTask *self, SEL _cmd);
id   MangoTask_inst_free(MangoTask *self, SEL _cmd);
kern_return_t MangoTask_inst_initKernel(MangoTask *self, SEL _cmd);
kern_return_t MangoTask_inst_create(MangoTask *self, SEL _cmd, mango_task_t **out, const char *name);
kern_return_t MangoTask_inst_terminate(MangoTask *self, SEL _cmd, mango_task_t *task);
mango_task_t *MangoTask_inst_lookup(MangoTask *self, SEL _cmd, mach_task_t task_id);
kern_return_t MangoTask_inst_insertPort(MangoTask *self, SEL _cmd, mango_task_t *task, mach_port_name_t name, mach_port_t port);
kern_return_t MangoTask_inst_removePort(MangoTask *self, SEL _cmd, mango_task_t *task, mach_port_name_t name);
mach_port_t MangoTask_inst_bootstrapPort(MangoTask *self, SEL _cmd, mango_task_t *task);
kern_return_t MangoTask_inst_threadCreate(MangoTask *self, SEL _cmd, mango_task_t *task, mango_thread_t **out);
kern_return_t MangoTask_inst_threadTerminate(MangoTask *self, SEL _cmd, mango_thread_t *thread);
kern_return_t MangoTask_inst_threadSuspend(MangoTask *self, SEL _cmd, mango_thread_t *thread);
kern_return_t MangoTask_inst_threadResume(MangoTask *self, SEL _cmd, mango_thread_t *thread);
kern_return_t MangoTask_inst_launchInit(MangoTask *self, SEL _cmd, const char *root);

#endif /* MANGO_TASK_MANGOTASK_H */
