/*
 * mango/ipc/MangoIPC.h
 *
 * Objective-C class for the Mango IPC subsystem.
 *
 * IPC in Mango is built on Unix domain socket pairs.  Each Mach
 * port that has a receive right gets its own socket pair.  Senders
 * write formatted mach_msg_t structures into the socket; receivers
 * read them out.
 */

#ifndef MANGO_IPC_MANGOIPC_H
#define MANGO_IPC_MANGOIPC_H

#include "../mach/mach_types.h"
#include "../mach/mach_msg.h"
#include "../mach/mach_port.h"

#ifdef __OBJC__
#include <objc/Object.h>
#endif

/* -----------------------------------------------------------------------
 *  Service entry
 * ----------------------------------------------------------------------- */

typedef struct ipc_service_entry {
    char                name[128];
    mach_port_t         port;
    BOOL                in_use;
} ipc_service_entry_t;

#define IPC_MAX_SERVICES  128

extern ipc_service_entry_t _ipc_service_table[IPC_MAX_SERVICES];
extern int                 _ipc_service_count;
extern mach_port_t         _ipc_bootstrap_port;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

id   MangoIPC_inst_init(MangoIPC *self, SEL _cmd);
id   MangoIPC_inst_free(MangoIPC *self, SEL _cmd);
kern_return_t MangoIPC_inst_register(MangoIPC *self, SEL _cmd, const char *name, mach_port_t port);
kern_return_t MangoIPC_inst_lookup(MangoIPC *self, SEL _cmd, const char *name, mach_port_t *out);
kern_return_t MangoIPC_inst_handleRequest(MangoIPC *self, SEL _cmd, mach_msg_t *request, mach_msg_t *reply);
kern_return_t MangoIPC_inst_msgSend(MangoIPC *self, SEL _cmd, mach_port_t dest, mach_msg_t *msg, mach_msg_size_t size, int timeout);
kern_return_t MangoIPC_inst_msgReceive(MangoIPC *self, SEL _cmd, mach_port_t src, mach_msg_t *msg, mach_msg_size_t size, int timeout);
kern_return_t MangoIPC_inst_msgRpc(MangoIPC *self, SEL _cmd, mach_port_t dest, mach_msg_t *msg, mach_msg_size_t sendSize, mach_msg_t *reply, mach_msg_size_t replySize, int timeout);

#endif /* MANGO_IPC_MANGOIPC_H */
