/*
 * mango/ipc/MangoIPC.h
 *
 * Objective-C class for the Mango IPC subsystem.
 *
 * IPC in Mango is built on Unix domain socket pairs.  Each Mach
 * port that has a receive right gets its own socket pair.  Senders
 * write formatted mach_msg_t structures into the socket; receivers
 * read them out.
 */

#ifndef MANGO_IPC_MANGOIPC_H
#define MANGO_IPC_MANGOIPC_H

#include "../mach/mach_types.h"
#include "../mach/mach_msg.h"
#include "../mach/mach_port.h"
#include <objc/objc.h>

/* -----------------------------------------------------------------------
 *  Service entry
 * ----------------------------------------------------------------------- */

typedef struct ipc_service_entry {
    char                name[128];
    mach_port_t         port;
    BOOL                in_use;
} ipc_service_entry_t;

#define IPC_MAX_SERVICES  128

extern ipc_service_entry_t ipc_service_table[IPC_MAX_SERVICES];
extern int                 ipc_service_count;
extern mach_port_t         ipc_bootstrap_port;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

typedef struct MangoIPC {
    struct objc_object *isa;
} MangoIPC;

/* Note: Method implementations are auto-generated by objcc preprocessor.
 * The preprocessor outputs function declarations at the start of the .m file.
 */

#endif /* MANGO_IPC_MANGOIPC_H */
