/*
 * mango/mach/MangoKernel.h
 *
 * Objective-C class for the Mango nanokernel lifecycle.
 *
 * This header is pure C -- it can be included by both .c and .m files.
 * When included by .m files, the @interface declaration is available.
 * When included by .c files, only the struct and C function decls are seen.
 */

#ifndef MANGO_MACH_MANGOKERNEL_H
#define MANGO_MACH_MANGOKERNEL_H

#include "mach_types.h"
#include <sys/types.h>
#include <signal.h>
#include <termios.h>

#ifdef __OBJC__
#include <objc/Object.h>
#endif

/* -----------------------------------------------------------------------
 *  Kernel version
 * ----------------------------------------------------------------------- */

#define MANGO_KERNEL_VERSION    "0.1.0"
#define MANGO_KERNEL_NAME       "Mango"

/* -----------------------------------------------------------------------
 *  Kernel boot flags
 * ----------------------------------------------------------------------- */

#define MANGO_BOOT_VERBOSE      0x0001
#define MANGO_BOOT_SINGLE_USER  0x0002
#define MANGO_BOOT_NO_INIT      0x0004
#define MANGO_BOOT_DEBUG        0x0008

/* -----------------------------------------------------------------------
 *  C struct for kernel state (used as ObjC ivars via preprocessor)
 * ----------------------------------------------------------------------- */

struct _MangoKernel_class_t;

struct MangoKernel {
    struct _MangoKernel_class_t *isa;
    BOOL                _initialized;
    BOOL                _running;
    uint32_t            _boot_flags;
    char                _userfs_root[512];
    pid_t               _kernel_pid;
    pid_t               _init_pid;
    mach_port_t         _host_port;
    mach_port_t         _host_priv_port;
    mach_port_t         _kernel_port;
    struct termios      _saved_term;
    BOOL                _have_saved_term;
};

typedef struct MangoKernel MangoKernel;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 *
 *  These follow the ObjC 1.0 C naming convention:
 *    ClassName_inst_methodName_  -- instance methods
 *    ClassName_cls_methodName_   -- class methods
 * ----------------------------------------------------------------------- */

/* Instance methods */
id   MangoKernel_inst_init(MangoKernel *self, SEL _cmd);
id   MangoKernel_inst_free(MangoKernel *self, SEL _cmd);
kern_return_t MangoKernel_inst_start(MangoKernel *self, SEL _cmd, uint32_t flags);
void MangoKernel_inst_loop(MangoKernel *self, SEL _cmd);
void MangoKernel_inst_shutdown(MangoKernel *self, SEL _cmd);
void MangoKernel_inst_banner(MangoKernel *self, SEL _cmd);
const char *MangoKernel_inst_userfsRoot(MangoKernel *self, SEL _cmd);
void MangoKernel_inst_setUserfsRoot_(MangoKernel *self, SEL _cmd, const char *path);
kern_return_t MangoKernel_inst_launchInit(MangoKernel *self, SEL _cmd, const char *root);

#endif /* MANGO_MACH_MANGOKERNEL_H */
