/*
 * mango/mach/MangoPort.h
 *
 * Objective-C class for Mach port management.
 *
 * Ports are emulated using Unix domain socket pairs.  Each port
 * with a receive right gets its own socket pair.  The kernel holds
 * one end and the owning task holds the other.
 */

#ifndef MANGO_MACH_MANGOPORT_H
#define MANGO_MACH_MANGOPORT_H

#include "mach_types.h"
#include "mach_msg.h"
#include <sys/un.h>

#ifdef __OBJC__
#include <objc/Object.h>
#endif

/* -----------------------------------------------------------------------
 *  Limits
 * ----------------------------------------------------------------------- */

#define MACH_PORT_TABLE_SIZE    256
#define MACH_PORT_QUEUE_MAX     64

/* -----------------------------------------------------------------------
 *  Port object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mach_port_object {
    mach_port_t         name;
    int                 type;
    int                 rights;
    int                 fd;
    int                 ref_count;
    BOOL                in_use;

    mach_msg_t         *queue[MACH_PORT_QUEUE_MAX];
    int                 queue_head;
    int                 queue_tail;
    int                 queue_count;
} mach_port_object_t;

/* -----------------------------------------------------------------------
 *  Port table (C globals)
 * ----------------------------------------------------------------------- */

extern mach_port_object_t _mango_port_table[MACH_PORT_TABLE_SIZE];
extern int                _mango_port_table_count;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

id   MangoPort_inst_init(MangoPort *self, SEL _cmd);
id   MangoPort_inst_free(MangoPort *self, SEL _cmd);
mach_port_t MangoPort_inst_allocate(MangoPort *self, SEL _cmd, int right);
kern_return_t MangoPort_inst_deallocate(MangoPort *self, SEL _cmd, mach_port_t port);
kern_return_t MangoPort_inst_destroy(MangoPort *self, SEL _cmd, mach_port_t port);
mach_port_object_t *MangoPort_inst_lookup(MangoPort *self, SEL _cmd, mach_port_t port);
int  MangoPort_inst_createSocketPair(MangoPort *self, SEL _cmd, mach_port_object_t *obj);
kern_return_t MangoPort_inst_queueMessage(MangoPort *self, SEL _cmd, mach_port_t port, mach_msg_t *msg);
mach_msg_t *MangoPort_inst_dequeueMessage(MangoPort *self, SEL _cmd, mach_port_t port);
kern_return_t MangoPort_inst_insertSend(MangoPort *self, SEL _cmd, mach_port_t port, mach_port_name_t name);
kern_return_t MangoPort_inst_insertReceive(MangoPort *self, SEL _cmd, mach_port_t port, mach_port_name_t name);

#endif /* MANGO_MACH_MANGOPORT_H */
