/*
 * mango/mach/MangoPort.h
 *
 * Objective-C class for Mach port management.
 *
 * Ports are emulated using Unix domain socket pairs.  Each port
 * with a receive right gets its own socket pair.  The kernel holds
 * one end and the owning task holds the other.
 */

#ifndef MANGO_MACH_MANGOPORT_H
#define MANGO_MACH_MANGOPORT_H

#include "mach_types.h"
#include "mach_msg.h"
#include <sys/un.h>
#include <objc/objc.h>

/* -----------------------------------------------------------------------
 *  Limits
 * ----------------------------------------------------------------------- */

#define MACH_PORT_TABLE_SIZE    256
#define MACH_PORT_QUEUE_MAX     64

/* -----------------------------------------------------------------------
 *  Port object (C struct)
 * ----------------------------------------------------------------------- */

typedef struct mach_port_object {
    mach_port_t         name;
    int                 type;
    int                 rights;
    int                 fd;
    int                 ref_count;
    BOOL                in_use;

    mach_msg_t         *queue[MACH_PORT_QUEUE_MAX];
    int                 queue_head;
    int                 queue_tail;
    int                 queue_count;
} mach_port_object_t;

/* -----------------------------------------------------------------------
 *  Port table (C globals)
 * ----------------------------------------------------------------------- */

extern mach_port_object_t mango_port_table[MACH_PORT_TABLE_SIZE];
extern int                mango_port_table_count;

/* -----------------------------------------------------------------------
 *  C-callable API (generated by objcc from @implementation)
 * ----------------------------------------------------------------------- */

typedef struct MangoPort {
    struct objc_object *isa;
} MangoPort;

/* Note: Method implementations are auto-generated by objcc preprocessor.
 * The preprocessor outputs function declarations at the start of the .m file.
 */

#endif /* MANGO_MACH_MANGOPORT_H */
